### ISSUE TITLE
Export OJS2 "Reader" user accounts for Konturen journal

### ISSUE THREAD

**Issue by carakey** [osulp/ojs#40]
**Related to / blocking completion of #27**

The journal _Konturen_ has a huge number of user accounts, and the UI tool times out trying to export them. I was able to export all users with account types other than "Reader" but cannot get the Readers. This is a self-sign-up type account so presumably these are mostly bots, but we'd like to get the good ones if possible. 

@wickr can you get this data from the backend?

**Comment by wickr** [comment]
User data is exported for all Konturen users, 57,227 total, with roles specified so you can get the Reader only ones. I'll share the Google Sheet, or you can have the raw TSV too if you want.

I started with this query and modified it some, but it includes user table values as well as biography and signature.
https://forum.pkp.sfu.ca/t/collaborative-list-of-spam-user-patterns/65190/2#c-to-describe-user-activity-in-order-to-identify-suspect-users-for-ojs-2x-13
I had to drop the comments inclusion because the total size was way too large. But bio/sig usually clearly indicate spam or not.

`roles` column values take the Role ID values and add them together for multiple roles per user. The Reader role value is 1048576, and I've added formatting in yellow where that matches exactly. This chart shows the other values, you can see some people with multiple roles get the values added together, but you should be able to ignore those since you got all the non-Reader roles already.
https://forum.pkp.sfu.ca/t/where-can-i-find-roles-table-in-ojs-3/72826/2

It looks like there's a handful of legit Reader-only accounts here but the vast majority are spam.

**Comment by carakey** [comment]
These worked out great. I was able to filter the Google sheet based on suspicious data and wound up with 50 probably-legitimate accounts, that I converted to XML and imported to OJS 3.
